<?php

use core\util\Session;

?>
<section class="pb_section pt-0 pb-0" id="section-contact">
    <div class="d-flex">
        <div class="pb_half py-5">

            <div class="row justify-content-center mb-5">
                <div class="col-md-12 text-center">
                    <h2 class="mb-4 text-uppercase pb_letter-spacing-2">Nova Mesa</h2>
                    <p class="text-center">Adicione as mesas do seu restaurante ou lanchonete, atraves delas seu cliente podera realizar reservas.</p>
                    <?php if (is_null($this->msg)) { } else {
                        ?><h3 id="msg"><?= $this->msg ?></h3>
                    <?php } ?>
                </div>
            </div>

            <div class="row justify-content-md-center">
                <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate id="envia" action="Request.php?class=NumMesaCtr&method=run&action=new&tipo=single">
                    <input type="hidden" name="id" id="id">
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="form-group">
                                <label for="numero_mesa">Numeo da Mesa:</label>
                                <input type="number" class="form-control rounded-0" name="numero_mesa" id="numero_mesa" maxlength="50" required>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="form-group">
                                <p>Caso queira adicionar vairas mesas, selecione um intervalo abaixo</p>
                                <label for="numero_mesa">Numeo da Mesa:</label>
                                <select class="form-control" name="intervalo" id="num_mesa">
                                    <option value="0" selected>Selecione um intervalo</option>
                                    <option value="10">1-10</option>
                                    <option value="20">1-20</option>
                                    <option value="30">1-30</option>
                                </select>
                                <!-- <input type="text" class="form-control rounded-0" name="numero_mesa" id="numero_mesa" maxlength="50" required> -->
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <input type="submit" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2  p-3 rounded-0" name="command" value="Salvar">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


</section>