<section class="pb_section pt-0 pb-0" id="section-contact">
    <div class="d-flex">
        <div class="pb_half py-5">

            <div class="row justify-content-center mb-5">
                <div class="col-md-12 text-center">
                    <h2 class="mb-4 text-uppercase pb_letter-spacing-2">Novo Usuario</h2>
                    <a class="botao" name="dsadas" href="#">Cadastrar Restaurante</a>
                </div>
            </div>

            <div class="row justify-content-md-center">


                <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate action="Request.php?class=PessoaCtr&method=run&action=new">
                    <input id="tipo" name="tipo" type="hidden" value="Fisica">
                    <input type="hidden" name="id" id="id">
                    <input type="hidden" name="id_pessoa" id="id_pessoa">

                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="name">Nome:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="nome_pessoa" id="nome_pessoa" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="telefone">Telefone:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="telefone_pessoa" id="telefone" maxlength="50">
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="celular">Celular:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="celular_pessoa" id="celular_pessoa" maxlength="50" required>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control p-2 rounded-0" name="email_pessoa" id="email_pessoa" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="cep">Cep:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="cep" id="cep" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="logradouro">Logradouro:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="logradouro" id="rua" maxlength="50" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="numero">Numero:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="numero" id="numero" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="complemento">Complemento:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="complemento" id="complemento" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="bairro">Bairro:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="bairro" id="bairro" maxlength="50" required>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="cidade">Cidade:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="cidade" id="cidade" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="uf">Estado:</label>
                                <input type="text" class="form-control p-2 rounded-0" name="uf" id="uf" maxlength="50" required>
                            </div>
                        </div>
                        <div class="col-md p-t-10">
                            <div class="cnpj invisible">
                                <div class="custom-file">
                                    <input type="file" value="" class="custom-file-input" id="image" name="image">
                                    <label class="custom-file-control" for="image">Selecione uma Imagem</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <div class="cpf">
                                    <label for="cpf ">CPF:</label>
                                    <input type="text" class="form-control p-2 rounded-0" name="cpf_fisica" id="cpf" maxlength="50">
                                </div>
                                <div class="cnpj invisible">
                                    <label for="cnpj_juridica">CNPJ:</label>
                                    <input type="text" class="form-control p-2 rounded-0" name="cnpj_juridica" id="cnpj_juridica" maxlength="50">
                                </div>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <div class="cnpj invisible">
                                    <label for="razao_social">Razão Social:</label>
                                    <input type="text" class="form-control p-2 rounded-0" name="razao_social" id="cpf" maxlength="50">
                                </div>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <div class="cnpj invisible">
                                    <label for="descricao">Descrição:</label>
                                    <textarea name="descricao" cols="30" rows="5" placeholder="Deixe aqui uma descrição">
                            </textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="login_pessoa">Login</label>
                                <input type="text" class="form-control p-2 rounded-0" name="login_pessoa" id="login_pessoa">
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">

                                <label for="senha_pessoa">Senha</label>
                                <input type="password" id="senha" class="form-control p-2 rounded-0" name="senha_pessoa" id="senha_pessoa" required> <!-- don't show the password -->                                
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">

                                <label for="senha_pessoa">Confirme Senha</label>
                                <input type="password" id="confSenha" class="form-control p-2 rounded-0" required> <!-- don't show the password -->
                                <div class="valid-feedback">
                                    OK!!!
                                </div>
                                <div class="invalid-feedback">
                                    As senhas nao sao Iguais!!!
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <input type="submit" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2  p-3 rounded-0" name="command" value="Salvar">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</section>
<!-- END section -->
<!-- cep character varying(9),
    logradouro character varying(50),
    numero integer,
    complemento character varying(70),
    bairro character varying(50),
    cidade character varying(50),
    uf character(2), -->

<!-- nome_pessoa varchar (70) not null,
telefone_pessoa varchar(15),
celular_pessoa varchar(15),
email_pessoa varchar(50),
login_pessoa varchar(16) not null,
senha_pessoa varchar(16) not null, -->