<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card" id="userdados">

                <div class="card-body">
                    <div class="card-title mb-4">
                        <p class="text-center">Meus Dados</p>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Nome:</label>
                                </div>
                                <input id="id_pessoa" type="hidden" value="<?= $this->model->getId() ?>">
                                <input type="hidden" name="tipo" value="Fisica">
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getNome_pessoa() ?>
                                </div>
                            </div>
                            <hr />

                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Telefone</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getTelefone_pessoa() ?>
                                </div>
                            </div>
                            <hr />


                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Celular:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getCelular_pessoa() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Email:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getEmail_pessoa() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Cpf:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getCpf_fisica() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Cep:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getCep() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Logradouro:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getLogradouro() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Numero:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getNumero() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Complemento:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getComplemento() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Bairro:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getBairro() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Cidade:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getCidade() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Estado:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getUf() ?>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3 col-md-2 col-5">
                                    <label style="font-weight:bold;">Login:</label>
                                </div>
                                <div class="col-md-8 col-6">
                                    <?= $this->model->getLogin_pessoa() ?>
                                </div>
                            </div>
                            <hr />                                                       
                         
                            <a class="p-r-10" href="Request.php?class=PessoaCtr&method=showView" data-toggle="tooltip" data-placement="top" title="Altere suas informações!!!"><button class="btn btn-focus">Alterar</button></a>

                            <a id="pessoadados" href="#" data-toggle="tooltip" data-placement="top" title="Exclua sua Conta.."><button class="btn btn-focus">Excluir</button></a>
                        </div>

                    </div>
                </div>


            </div>

        </div>
    </div>
</div>