<section class="pb_section pt-0 pb-0" id="section-contact">
    <div class="d-flex">
        <div class="pb_half py-5">
            <div class="row justify-content-center mb-5">
                <div class="col-md-12 text-center">
                    <h2 class="mb-4 text-uppercase pb_letter-spacing-2">Entre em Contato conosco</h2>
                    <p class="text-center">Tem alguma </p>
                </div>
            </div>
            <div class="justify-content-md-center">

                <form method="post" class="contato needs-validation" novalidate action="#">



                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="numero_mesa">Nome</label>
                                <input type="text" class="form-control" name="nome" id="">
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="numero_mesa">Email</label>
                                <input type="text" class="form-control" name="nome" id="">
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Mensagem</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md">
                            <div class="form-group">
                                <input type="submit" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2  p-3 rounded-0" value="Enviar">
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</section>