<?php

use core\util\Session;

// if (!isset($_SESSION)) session_start();
?>
<section class="pb_section pt-0 pb-0" id="section-contact">
    <div class="d-flex">
        <div class="pb_half py-5">

            <div class="row justify-content-center mb-5">
                <div class="col-md-12 text-center">
                    <h2 class="mb-4 text-uppercase pb_letter-spacing-2">Nova Categoria</h2>
                    <p class="text-center">Caso tenha algum produto que precisa de uma nova categoria, é possivel adiciona-la por aqui!!</p>
                    <?php if (is_null($this->msg)) { } else {
                        ?><h3 id="msg"><?= $this->msg ?></h3>
                    <?php } ?>
                </div>
            </div>

            <div class="justify-content-md-center">
                <form method="post" enctype="multipart/form-data" class="categoria needs-validation" novalidate action="Request.php?class=CategoriaCtr&method=run&action=new">                    
                    <input type="hidden" name="id" id="id">                    
                    <div class="form-row">
                        <div class="col-md-12 col-lg-12">
                            <div class="form-group">
                                <label for="nome_categoria">Categoria:</label>
                                <input type="text" class="form-control rounded-0" name="nome_categoria" id="nome_categoria" maxlength="50" required>
                            </div>
                        </div>                        
                    </div>                            
                    <div class="form-row">
                        <div class="col-md">
                            <div class="form-group">
                                <input type="submit" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2  p-3 rounded-0" name="command" value="Salvar">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</section>