<h1 class="text-center p-b-50">Produtos cadastrados no estabelecimento</h1>

<?php if (is_null($this->msg)) { } else {
    ?><h3 class="text-center p-b-10" id="msg"><?= $this->msg ?></h3>
<?php } ?>

<?php if (!is_null($this->produto)) { ?>
    <div class="p-l-10 p-b-10">
        <!-- <button class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 " id="relatorio">Funcionarios</button> -->
    </div>
    <div class="table-responsive">

        <table class="table-stripped" id="myTable" style="width:95%;">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">NOME</th>
                    <th class="text-center">UNIDADE</th>
                    <th class="text-center">PREÇO</th>
                    <th class="text-center">ESTOQUE</th>
                    <th class="text-center">CATEGORIA</th>
                    <th class="text-center">IMAGEM</th>
                    <th class="text-center">ALTERAR</th>
                    <th class="text-center">EXCLUIR</th>

                </tr>
            </thead>


            <tbody>
                <!-- 12 -->

                <?php foreach ($this->produto as $row) { ?>
                    <tr>

                        <td id="id" class="text-center"> <?= $row->getId() ?></td>
                        <td class="text-center"> <?= $row->getNome_produto() ?></td>
                        <td id="id" class="text-center"> <?= $row->getUnidade_produto() ?></td>
                        <td class="text-center"> <?= $row->getPreco_produto() ?></td>
                        <td id="id" class="text-center"> <?= $row->getQuant_estoque() ?></td>
                        <td class="text-center"> <?= $row->getCategoria()->getNome_categoria() ?></td>

                        <td class="text-center">
                            <a class="image" href="app/img/<?= $row->getImagem() ?>">
                                <img id="imgprod" src="app/img/<?= $row->getImagem() ?>">
                            </a>
                        </td>


                        <td class="text-center"><a href="Request.php?class=ProdutoCtr&method=showView&id=<?= $row->getId() ?>" id="alterar" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">ALTERAR</a></td>

                        <td class="excluir text-center" caminho="Request.php?class=ProdutoCtr&method=delete&id=<?= $row->getId() ?>"><a href="#" class="teste btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">EXCLUIR</a></td>

                    </tr>
                <?php } ?>


            </tbody>
        </table>


    <?php } else { ?>
        <p class="text-center">Sem Produtos Ainda</p>
    <?php } ?>
    </div>