<?php

use core\util\Session;
?>

<h1 class="text-center p-5">Bem vindo ao dashboard do seu resturante,
    <?= Session::getSession('active_user')->getNome_pessoa() ?></h1>
<?php if (isset($this->msg)) { ?>
    <h2 class="text-center" id="msg"><?= $this->msg ?></h2>
<?php } ?>

<?php if (!is_null($this->mesas)) { ?>
    <div class="p-l-10 p-b-10">
        <!-- <button class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 " id="relatorio">Funcionarios</button> -->
    </div>
    <div class="table-responsive">
        <table class="table-stripped" id="mesas" style="width:100%;">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">NOME</th>                    
                    <th class="text-center">CELULAR</th>
                    <th class="text-center">EMAIL</th>
                    <th class="text-center">NUMERO MESA</th>
                    
                   
                    <th class="text-center">ALTERAR</th>
                    <th class="text-center">EXCLUIR</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->mesas as $row) { ?>
                    <tr>
                        <td id="id" class="text-center"> <?= $row->getId() ?></td>
                        <td class="text-center"> <?= $row->getId_pessoa()->getNome_pessoa() ?></td>                       
                        <td class="text-center"> <?= $row->getId_pessoa()->getCelular_pessoa() ?></td>
                        <td class="text-center"> <?= $row->getId_pessoa()->getEmail_pessoa() ?></td>
                        
                        <td class="text-center"> <?= $row->getNumero_mesa()->getNum_mesa() ?></td>                        
                        <td class="excluir text-center" caminho="Request.php?class=FuncCtr&method=delete&id=<?= $row->getId() ?>"> <a href="#" class="teste btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">ALTERAR</a></td>

                        <td class="excluir text-center" caminho="Request.php?class=FuncCtr&method=delete&id=<?= $row->getId() ?>"> <a href="#" class="teste btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">EXCLUIR</a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    <?php } else { ?>
        <p class="text-center">Sem Mesas Reservadas Ainda</p>
    <?php } ?>
    </div>

<?php if (!is_null($this->vendas)) { ?>
    <div class="p-l-10 p-b-10">
        <button class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 " id="relatorio">Relatório</button>
    </div>
    <div class="table-responsive">
        <table class="table-stripped" id="myTable" style="width:100%;">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NOME</th>
                    <th>EMAIL</th>
                    <th>CPF</th>
                    <th>TOTAL</th>
                    <th>DATA</th>
                    <th>HORA</th>
                    <th>TIPO</th>
                    <th>PRODUTO</th>
                    <th>UNITARIO</th>
                    <th>QUANTIDADE</th>
                </tr>
            </thead>
            <tbody>
                <!-- 12 -->
                <tr>
                    <?php foreach ($this->vendas as $row) { ?>
                        <td> <?= $row['id_pessoa'] ?></td>
                        <td> <?= $row['nome_pessoa'] ?></td>
                        <td> <?= $row['email_pessoa'] ?></td>
                        <td> <?= $row['cpf_fisica'] ?></td>
                        <td> <?= $row['preco_total'] ?></td>
                        <td> <?= $row['data_venda'] ?></td>
                        <td> <?= $row['hora_venda'] ?></td>
                        <td> <?= $row['tipo_pagamento'] ?></td>
                        <td> <?= $row['nome_produto'] ?></td>
                        <td> <?= $row['preco_produto'] ?></td>
                        <td> <?= $row['quantidade'] ?></td>
                    <?php } ?>
                </tr>

            </tbody>
        </table>
    </div>
<?php } else { ?>
    <p class="text-center">Sem Vendas Ainda</p>
<?php } ?>