<?php

use core\util\Session;
?>

<h1 class="text-center p-5">Bem vindo ao dashboard do seu resturante,
    <?= Session::getSession('active_user')->getNome_pessoa() ?></h1>
<?php if (isset($this->msg)) { ?>
    <h2 class="text-center" id="msg"><?= $this->msg ?></h2>
<?php } ?>

<?php if (!is_null($this->vendas)) { ?>
    <div class="p-l-10 p-b-10">
    <button class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 " id="relatorio">Relatório</button>
    </div>
    <div class="table-responsive">
        <table class="table-stripped" id="myTable" style="width:100%;">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NOME</th>
                    <th>EMAIL</th>
                    <th>CPF</th>
                    <th>TOTAL</th>
                    <th>DATA</th>
                    <th>HORA</th>
                    <th>TIPO</th>
                    <th>PRODUTO</th>
                    <th>UNITARIO</th>
                    <th>QUANTIDADE</th>
                </tr>
            </thead>
            <tbody>
                <!-- 12 -->
                <tr>
                    <?php foreach ($this->vendas as $row) { ?>
                        <td> <?= $row['id_pessoa'] ?></td>
                        <td> <?= $row['nome_pessoa'] ?></td>
                        <td> <?= $row['email_pessoa'] ?></td>
                        <td> <?= $row['cpf_fisica'] ?></td>
                        <td> <?= $row['preco_total'] ?></td>
                        <td> <?= $row['data_venda'] ?></td>
                        <td> <?= $row['hora_venda'] ?></td>
                        <td> <?= $row['tipo_pagamento'] ?></td>
                        <td> <?= $row['nome_produto'] ?></td>
                        <td> <?= $row['preco_produto'] ?></td>
                        <td> <?= $row['quantidade'] ?></td>
                    <?php } ?>
                </tr>

            </tbody>
        </table>
    <?php } else { ?>
        <p class="text-center">Sem Vendas Ainda</p>
    <?php } ?>
    </div>