<?php

use core\util\Session;

// if (!isset($_SESSION)) session_start();
?>
<section class="pb_section" id="section-about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mb-5">
            <div class="row">              
              <div class="col">
                <p><img src="<?=$this->desc->getImagem()?>" alt="Instant Image" class="img-fluid"></p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 pl-lg-5 pl-lg-0">
            <h2 class="mb-4 text-uppercase pb_letter-spacing-2"><?=$this->desc->getRazao_social()?></h2>
            <p><?=$this->desc->getDescricao()?>.</p>

            <p><?=$this->desc->getDescricao()?>.</p>
            <p><a href="#section-menu" class="smoothscroll text-danger text-uppercase">Veja nosso menu<i class="ion-arrow-down-c"></i></a></p>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

<section class="pb_section" id="section-menu">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-10 text-center">
                <h2 class="mb-4 text-uppercase pb_letter-spacing-2">Menu</h2>
            </div>
        </div>
        <div class="row">
            <div class="col">

                <ul class="nav justify-content-center pb_tab_v1">
                    <li class="nav-item">
                        <a class="nav-link active p-3" data-toggle="list" href="#food" role="tab">Food</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-3" data-toggle="list" href="#drinks" role="tab">Drinks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-3" data-toggle="list" href="#salads" role="tab">Salads</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="food" role="tabpanel">
                        <div class="row">
                            
                            <div class="col-md">
                                <ul class="list-unstyled pb_food-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Eggplant Parmiagana</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>20.75</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Fried Calamari</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>18.00</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Sausage and Pepper</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>10.25</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Potato and Egg</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>21.95</span></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="drinks" role="tabpanel">
                        <div class="row">
                            <div class="col-md">
                                <ul class="list-unstyled pb_food-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Fountain Soda</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>10.95</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Fresh Juices</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>12.50</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Coffee/Tea</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>5.35</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Unsweetened Tea</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>12.50</span></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md">
                                <ul class="list-unstyled pb_food-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Fountain Soda</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>10.95</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Fresh Juices</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>12.50</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Coffee/Tea</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>5.35</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Unsweetened Tea</h3>
                                                <p class="mb-0">Far far away, behind the word mountains..</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>12.50</span></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="salads" role="tabpanel">
                        <div class="row">
                            <div class="col-md">
                                <ul class="list-unstyled pb_food-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Caesars Salad</h3>
                                                <p class="mb-0">Romaine lettuce, croutons, and grated cheese</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>13.95</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Garden Salad</h3>
                                                <p class="mb-0">Mixed greens, tomato, cucumber &amp; black olives</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>15.50</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Baby Greens</h3>
                                                <p class="mb-0">Mixed greens, fresh mozzarella, tomato &ampl toasted peppers</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>17.35</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Cold Antipasto</h3>
                                                <p class="mb-0">Romaine lettuce, croutons, and grated cheese</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>11.50</span></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md">
                                <ul class="list-unstyled pb_food-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Caesars Salad</h3>
                                                <p class="mb-0">Romaine lettuce, croutons, and grated cheese</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>22.95</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Garden Salad</h3>
                                                <p class="mb-0">Mixed greens, tomato, cucumber &amp; black olives</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>11.50</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Baby Greens</h3>
                                                <p class="mb-0">Mixed greens, fresh mozzarella, tomato &ampl toasted peppers</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>14.35</span></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <h3 class="pb_font-18 font-weight-bold">Cold Antipasto</h3>
                                                <p class="mb-0">Romaine lettuce, croutons, and grated cheese</p>
                                            </div>
                                            <div class="col-lg-2"><span class="price"><sup>$</sup>15.50</span></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END section -->