        <!-- </section> 
        <footer>
            <small>Fatec Jales</small>
        </footer>
    </div> 
    
</body>
</html> -->


        <footer class="pb_footer bg-light" role="contentinfo">
          <div class="container">
            <div class="row text-center">
              <div class="col">
                <ul class="list-inline">
                  <li class="list-inline-item"><a href="#" class="p-2"><i class="fa fa-facebook"></i></a></li>
                  <li class="list-inline-item"><a href="#" class="p-2"><i class="fa fa-twitter"></i></a></li>
                  <li class="list-inline-item"><a href="#" class="p-2"><i class="fa fa-instagram"></i></a></li>
                  <li class="list-inline-item"><a href="#" class="p-2"><i class="fa fa-tripadvisor"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="col text-center">
                <p>&copy; 2017 <a href="https://uicookies.com/wrapbootstrap/instant">Instant</a>. All Rights Reserved. Designed by <a href="https://uicookies.com/">uiCookies</a></p>
              </div>
            </div>
          </div>
        </footer>

        <!-- loader -->
        <!-- <div id="pb_loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#FDA04F"/></svg></div> -->


        <script src="core/vendor/assets/js/jquery.min.js"></script>
        <script src="core/vendor/assets/js/jquery.validate.min.js"></script>
        <script src="core/vendor/js/datatables.js"></script>
        <script src="core/vendor/js/dataTables.bootstrap4.js"></script>



        <!-- <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script> -->


        <script src="core/vendor/js/jquery.mask.js"></script>
        <script src="core/vendor/assets/js/popper.min.js"></script>
        <script src="core/vendor/assets/js/bootstrap.min.js"></script>

        <script src="app/js/valida_form.js"></script>
        <script src="core/vendor/js/main.js"></script>

        <script src="app/js/principal.js"></script>
        <script src="app/js/busca_cep.js"></script>

        <script src="core/vendor/assets/js/slick.min.js"></script>
        <script src="core/vendor/assets/js/jquery.mb.YTPlayer.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

        <script src="core/vendor/assets/js/jquery.waypoints.min.js"></script>
        <script src="core/vendor/assets/js/jquery.easing.1.3.js"></script>

        <script src="core/vendor/assets/js/jquery.magnific-popup.min.js"></script>
        <script src="core/vendor/assets/js/magnific-popup-options.js"></script>


        <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="assets/js/google-map.js"></script> -->

        <script src="core/vendor/assets/js/main.js"></script>

        </body>

        </html>