<?php

use core\Application;
?>

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Quick Path</title>
    <meta name="description" content="Quick Path">
    <meta name="keywords" content="Quick Path">

    <link rel="stylesheet" href="core/vendor/assets/css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="core/vendor/assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="core/vendor/assets/css/magnific-popup.css">

    <link rel="stylesheet" href="core/vendor/assets/fonts/fontawesome/css/font-awesome.min.css">


    <link rel="stylesheet" href="core/vendor/assets/css/slick.css">

    <link rel="stylesheet" href="core/vendor/assets/css/helpers.css">
    <link rel="stylesheet" href="core/vendor/assets/css/style.css">
    <link rel="stylesheet" href="core/vendor/assets/css/restaurant.css">

    <link rel="stylesheet" href="app/css/style.css">
</head>

<body>


    <div class="probootstrap-loader"></div>
    <!-- END loader -->

    <nav class="navbar navbar-expand-lg navbar-dark pb_navbar pb_scrolled-light" id="pb-navbar">
        <div class="container">
            <a class="navbar-brand d-xl-none d-lg-none d-md-block d-sm-block" href="/">
                <img src="core/vendor/assets/images/restaurant/logo.png" alt="Instant Logo" class="light">
                <img src="core/vendor/assets/images/restaurant/logo-dark.png" alt="Instant Logo" class="dark">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-navbar" aria-controls="probootstrap-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span><i class="ion-navicon"></i></span>
            </button>
            <div class="collapse navbar-collapse justify-content-md-center" id="probootstrap-navbar">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="index.php">Home</a></li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-about">About</a></li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-menu">Menu</a></li>
                    <li class="nav-item logo-center d-xl-block d-lg-block d-md-none d-sm-none d-none">
                        <a class="nav-link text-uppercase pb_letter-spacing-2" href="index.html">
                            <img src="core/vendor/assets/images/restaurant/logo.png" alt="Instant Logo" class="light">
                            <img src="core/vendor/assets/images/restaurant/logo-dark.png" alt="Instant Logo" class="dark">
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="Request.php?class=PessoaCtr&method=showView&action=new">Cadastro</a></li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-uppercase pb_letter-spacing-2" data-toggle="modal" data-target="#modalExemplo">
                            login
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->

    <section class="pb_cover_v1 cover-bg-black cover-bg-opacity-4 text-center" style="background-image: url(assets/images/restaurant/1900x1200/img_1.jpg)" id="section-home">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-9  order-md-1">
                    <a href="https://vimeo.com/channels/staffpicks/93951774" class="play popup-vimeo"><i class="ion-ios-play"></i></a>
                    <h2 class="heading mb-3"><?php Application::$APP_NAME ?></h2>
                    <div class="sub-heading">
                        <p class="mb-5">Frase indefinida ainda</p>
                        <p> Acesse nosso App e deixe tudo ainda mais facil (em breve)</p>
                    </div>

                    <a href="#section-contact" role="button" class="btn smoothscroll pb_outline-light rounded-0 btn-xl pb_font-13 pb_letter-spacing-2 mb-3 p-3">Link</a>

                    <p><a href="#section-contact" role="button" class="btn smoothscroll pb_outline-light rounded-0 btn-xl pb_font-13 pb_letter-spacing-2 p-3">Reserve uma Mesa</a></p>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Título do modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="Request.php?class=PessoaCtr&method=doLogin">
                        <label for="login_pessoa">Login</label><br>
                        <input type="text" name="login_pessoa" id="login_pessoa"><br>
                        <label for="senha_pessoa">Senha</label><br>
                        <input type="password" name="senha_pessoa" id="senha_pessoa"><br>
                        <input type="submit" name="command" value="OK">
                        <input type="reset" name="command" value="Limpar">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="button" class="btn btn-primary">Salvar mudanças</button>
                </div>
            </div>
        </div>
    </div>
    <!-- END section -->