<!-- 

<!DOCTYPE html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Título aqui!</title>
    <link rel="stylesheet" href="core/vendor/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="app/css/style.css">
</head>

<body>
    <div id="container">
        <header>                    
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="index.php"><//?= Application::$APP_NAME ?></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.php">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=PessoaCtr&method=showView&action=new">Cadastrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=CategoryCtr&method=showList">Listar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=FlowCtr&method=showView">Lançamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=FlowCtr&method=showList">Listar</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        </header>
        <section id="active_user">
            <p>Usuário ativo: <//?=$this->activeUserName?></p>            
        </section>
        <nav>    
        <nav>
            <ul>
                <li><a href="index.php">Início</a></li>
                <li>
@ -38,5 +74,5 @@ use core\Application;
                </li>
                <a href="Request.php?class=UserCtr&method=doLogout">Sair</a>
            </ul>
        </nav>
        </nav>
        <section id="content"> -->

<?php

use core\Application;
?>

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Instant &mdash; Free Restaurant Bootstrap 4 Template by uicookies.com</title>
    <meta name="description" content="free Bootstrap 4 Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

    <!-- <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600|Montserrat:200,300,400, 600, 700" rel="stylesheet"> -->

    

    <link rel="stylesheet" href="core/vendor/assets/css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="core/vendor/assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="core/vendor/assets/css/magnific-popup.css">

    <link rel="stylesheet" href="core/vendor/assets/fonts/fontawesome/css/font-awesome.min.css">


    <link rel="stylesheet" href="core/vendor/assets/css/slick.css">

    <link rel="stylesheet" href="core/vendor/assets/css/helpers.css">
    <link rel="stylesheet" href="core/vendor/assets/css/style.css">
    <link rel="stylesheet" href="core/vendor/assets/css/restaurant.css">
    <link rel="stylesheet" href="app/css/style.css">
</head>

<body data-spy="scroll" data-target="#pb-navbar" data-offset="200">


    <div class="probootstrap-loader"></div>
    <!-- END loader -->

    <nav class="navbar navbar-expand-lg navbar-dark pb_navbar pb_scrolled-light" id="pb-navbar">
        <div class="container">
            <a class="navbar-brand d-xl-none d-lg-none d-md-block d-sm-block" href="/">
                <img src="core/vendor/assets/images/restaurant/logo.png" alt="Instant Logo" class="light">
                <img src="core/vendor/assets/images/restaurant/logo-dark.png" alt="Instant Logo" class="dark">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-navbar" aria-controls="probootstrap-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span><i class="ion-navicon"></i></span>
            </button>
            <div class="collapse navbar-collapse justify-content-md-center" id="probootstrap-navbar">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="index.php">Home</a></li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-about">About</a></li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-menu">Menu</a></li>
                    <li class="nav-item logo-center d-xl-block d-lg-block d-md-none d-sm-none d-none">
                        <a class="nav-link text-uppercase pb_letter-spacing-2" href="index.html">
                            <img src="core/vendor/assets/images/restaurant/logo.png" alt="Instant Logo" class="light">
                            <img src="core/vendor/assets/images/restaurant/logo-dark.png" alt="Instant Logo" class="dark">
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="Request.php?class=PessoaCtr&method=showView&action=new">Cadastro</a></li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-events">Events</a></li>
                    <li class="nav-item"><a class="nav-link text-uppercase pb_letter-spacing-2" href="#section-contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->

    <section class="pb_cover_v1 cover-bg-black cover-bg-opacity-4 text-center" style="background-image: url(assets/images/restaurant/1900x1200/img_1.jpg)" id="section-home">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-9  order-md-1">
            <a href="https://vimeo.com/channels/staffpicks/93951774" class="play popup-vimeo"><i class="ion-ios-play"></i></a>
            <h2 class="heading mb-3"><?php Application::$APP_NAME ?></h2>
            <div class="sub-heading"><p class="mb-5">Tenha sempre o caminho mais rapido para satisfazer sua fome, encontre restaurantes e lanchonetes parceiras do Quick Path</p><p> Acesse tambem nosso App e deixe tudo ainda mais facil</p></div>
            
            <a href="#section-contact" role="button" class="btn smoothscroll pb_outline-light rounded-0 btn-xl pb_font-13 pb_letter-spacing-2 mb-3 p-3">Link</a>
            
            <p><a href="#section-contact" role="button" class="btn smoothscroll pb_outline-light rounded-0 btn-xl pb_font-13 pb_letter-spacing-2 p-3">Reserve uma Mesa</a></p>
          </div>  
        </div>
      </div>
    </section>
    <!-- END section -->