<?php

use core\Application;
?>

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Quick Path</title>
    <meta name="description" content="Quick Path">
    <meta name="keywords" content="Quick Path">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link rel="stylesheet" href="core/vendor/assets/css/bootstrap/bootstrap.css">

    <link rel="stylesheet" href="core/vendor/assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="core/vendor/assets/css/magnific-popup.css">

    <link rel="stylesheet" href="core/vendor/assets/fonts/fontawesome/css/font-awesome.min.css">


    <link rel="stylesheet" href="core/vendor/assets/css/slick.css">

    <link rel="stylesheet" href="core/vendor/assets/css/helpers.css">
    <link rel="stylesheet" href="core/vendor/assets/css/style.css">
    <link rel="stylesheet" href="core/vendor/assets/css/restaurant.css">
    <link rel="stylesheet" href="core/vendor/assets/css/util.css">
    <link rel="stylesheet" href="core/vendor/css/datatables.css">
    <link rel="stylesheet" href="core/vendor/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="app/css/style.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="index.php"><?= Application::$APP_NAME ?></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=DashboardCtr&method=showView&action=show">Meus Dados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=DashboardCtr&method=showView&action=new">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Caixa</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Funcionario
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Request.php?class=FuncCtr&method=showView&action=new">Cadastrar</a>

                            <a class="dropdown-item" href="Request.php?class=FuncCtr&method=showView&action=show">Listar</a>
                           
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cargos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Request.php?class=CargoCtr&method=showView&action=new">Cadastrar</a>

                            <a class="dropdown-item" href="Request.php?class=CargoCtr&method=showView&action=show">Listar</a>   
                        
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Produto
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="Request.php?class=ProdutoCtr&method=showView&action=new">Cadastrar</a>

                            <a class="dropdown-item" href="Request.php?class=ProdutoCtr&method=showView&action=show">Listar</a>

                            
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categoria
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="Request.php?class=CategoriaCtr&method=showView&action=new">Cadastrar</a>

                            <a class="dropdown-item" href="Request.php?class=CategoriaCtr&method=showView&action=show">Listar</a>

                            
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mesa
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Request.php?class=NumMesaCtr&method=showView&action=new">Cadastrar</a>

                            <a class="dropdown-item" href="Request.php?class=NumMesaCtr&method=showView&action=show">Listar</a>                           
                        </div>
                    </li>
                  
                    <li class="nav-item">
                        <a class="nav-link" href="Request.php?class=PessoaCtr&method=doLogout">Sair</a>
                    </li>
                </ul>                
            </div>
        </nav>
    </header>