    <section class="pb_section" id="section-about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mb-5">
            <div class="row">
              <div class="col">
                <p><img src="app/img/logo/PNG_1.png" alt="Instant Image" class="img-fluid"></p>
              </div>
              <!-- <div class="col">
                <p><img src="assets/images/restaurant/800x975/img_2.jpg" alt="Instant Image" class="img-fluid"></p>
              </div> -->
            </div>
          </div>
          <div class="col-lg-4 pl-lg-5 pl-lg-0">
            <h2 class="mb-4 text-uppercase pb_letter-spacing-2">Quick Path</h2>
            <p>Quick Path tem o intuito de trazer agilidade na hora das pessoas escolherem o que querem e onde querem comer!! Quick Path em tradução livre "Caminho Rápido", sendo assim somos um caminho rapido para você!! </p>

           
          </div>
        </div>
      </div>
    </section>