<h1 class="text-center p-b-50">Cargos cadastrados no estabelecimento</h1>

<?php if (is_null($this->msg)) { } else {
    ?><h3 class="text-center p-b-10" id="msg"><?= $this->msg ?></h3>
<?php } ?>

<?php if (!is_null($this->cargos)) { ?>
    <div class="p-l-10 p-b-10">
        <!-- <button class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 " id="relatorio">Funcionarios</button> -->
    </div>
    <div class="table-responsive">

        <table class="table-stripped" id="myTable" style="width:100%;">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">NOME</th>
                    <th class="text-center">ALTERAR</th>
                    <th class="text-center">EXCLUIR</th>
                </tr>
            </thead>


            <tbody>
                <!-- 12 -->

                <?php foreach ($this->cargos as $row) { ?>
                    <tr>

                        <td id="id" class="text-center"> <?= $row->getId() ?></td>
                        <td class="text-center"> <?= $row->getNome_cargo() ?></td>

                        <td class="text-center"><a  href="Request.php?class=CargoCtr&method=showView&id=<?= $row->getId() ?>" id="alterar" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">ALTERAR</a></td>

                        <td class="excluir text-center" caminho="Request.php?class=CargoCtr&method=delete&id=<?= $row->getId() ?>"><a href="#" id="excluir" class="teste btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">EXCLUIR</a></td>

                    </tr>
                <?php } ?>


            </tbody>
        </table>


    <?php } else { ?>
        <p class="text-center">Sem Cargos Ainda</p>
    <?php } ?>
    </div>