<h1 class="text-center p-b-50">Funcionarios cadastrados no estabelecimento</h1>

<?php if (is_null($this->msg)) { } else {
    ?><h3 class="text-center p-b-10" id="msg"><?= $this->msg ?></h3>
<?php } ?>

<?php if (!is_null($this->funcs)) { ?>
    <div class="p-l-10 p-b-10">
        <!-- <button class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 " id="relatorio">Funcionarios</button> -->
    </div>
    <div class="table-responsive">
        <table class="table-stripped" id="myTable" style="width:100%;">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">NOME</th>
                    <th class="text-center">TELEFONE</th>
                    <th class="text-center">CELULAR</th>
                    <th class="text-center">EMAIL</th>
                    <th class="text-center">CEP</th>
                    <th class="text-center">LOGRADOURO</th>
                    <th class="text-center">NUMERO</th>
                    <th class="text-center">COMPLEMENTO</th>
                    <th class="text-center">BAIRRO</th>
                    <th class="text-center">CIDADE</th>
                    <th class="text-center">UF</th>
                    <th class="text-center">CPF</th>
                    <th class="text-center">LOGIN</th>                    
                    <th class="text-center">CARGO</th>
                    <th class="text-center">SALARIO</th>
                    <th class="text-center">ALTERAR</th>
                    <th class="text-center">EXCLUIR</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->funcs as $row) { ?>
                    <tr>
                        <td id="id" class="text-center"> <?= $row->getId() ?></td>
                        <td class="text-center"> <?= $row->getNome_pessoa() ?></td>
                        <td class="text-center"> <?= $row->getTelefone_pessoa() ?></td>
                        <td class="text-center"> <?= $row->getCelular_pessoa() ?></td>
                        <td class="text-center"> <?= $row->getEmail_pessoa() ?></td>
                        <td class="text-center"> <?= $row->getCep() ?></td>
                        <td class="text-center"> <?= $row->getLogradouro() ?></td>
                        <td class="text-center"> <?= $row->getNumero() ?></td>
                        <td class="text-center"> <?= $row->getComplemento() ?></td>
                        <td class="text-center"> <?= $row->getBairro() ?></td>
                        <td class="text-center"> <?= $row->getCidade() ?></td>
                        <td class="text-center"> <?= $row->getUf() ?></td>
                        <td class="text-center"> <?= $row->getCpf_funcionario() ?></td>
                        <td class="text-center"> <?= $row->getLogin_pessoa() ?></td>
                        <td class="text-center"> <?= $row->getCargo()->getNome_cargo() ?></td>
                        <td class="text-center"> <?= $row->getSalario() ?></td>

                        <td class="text-center"> <a href="Request.php?class=FuncCtr&method=showView&action=update&id=<?= $row->getId() ?>" class="btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">ALTERAR</a></td>

                        <td class="excluir text-center" caminho="Request.php?class=FuncCtr&method=delete&id=<?= $row->getId() ?>"> <a href="#" class="teste btn pb_outline-dark pb_font-13 pb_letter-spacing-2 p-2 ">EXCLUIR</a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    <?php } else { ?>
        <p class="text-center">Sem Funcionarios Ainda</p>
    <?php } ?>
    </div>